
########### HYPER PARAMETERS ###########
n_iter: 2000
n_input: 1
pooling: "mean"
show_every: 50
########################################


seed: 1234

device: "cpu"

stft_cfg:
  n_fft: 512
  hop_length: 128
  window_type: hamming
  pad_mode: constant
  device: ${device}

net_cfg:
  _target_: networks.Unet

optim_cfg:
  _target_: torch.optim.Adam
  lr: 0.01
  weight_decay: 0

loss_cfg:
  _target_: torch.nn.L1Loss
